apiVersion: v1beta3
kind: Service
metadata:
  name: owncloud
  namespace: default
  labels:
    app: owncloud
spec:
  selector:
    app: owncloud
  ports:
  - name: https
    port: 443
    protocol: TCP
  - name: http
    port: 80
    protocol: TCP
